# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Label.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_url = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_url.setGeometry(QtCore.QRect(0, 50, 571, 61))
        self.textEdit_url.setObjectName("textEdit_url")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 171, 31))
        self.label.setObjectName("label")
        self.pushButton_dl = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dl.setGeometry(QtCore.QRect(460, 380, 101, 61))
        self.pushButton_dl.setObjectName("pushButton_dl")
        self.comboBox_videoformat = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_videoformat.setGeometry(QtCore.QRect(0, 160, 571, 41))
        self.comboBox_videoformat.setObjectName("comboBox_videoformat")
        self.comboBox_audioformat = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_audioformat.setGeometry(QtCore.QRect(0, 240, 571, 41))
        self.comboBox_audioformat.setObjectName("comboBox_audioformat")
        self.pushButton_getlists = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_getlists.setGeometry(QtCore.QRect(600, 50, 80, 23))
        self.pushButton_getlists.setObjectName("pushButton_getlists")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Url : "))
        self.pushButton_dl.setText(_translate("MainWindow", "Download"))
        self.pushButton_getlists.setText(_translate("MainWindow", "Get Lists"))
